# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    # driver: "gd"

    filter_sets:
        squared_thumbnail_small_portret:
            filters:
                thumbnail:
                    size: [ 100, 133 ]
                    mode: outbound
                    allow_upscale: true

        squared_thumbnail_medium_portret:
            filters:
                thumbnail:
                    size: [ 300, 399 ]
                    mode: outbound
                    allow_upscale: true

        squared_thumbnail_large_portret:
            filters:
                thumbnail:
                    size: [ 500, 665 ]
                    mode: outbound
                    allow_upscale: true

        squared_thumbnail_small_landscape:
            filters:
                thumbnail:
                    size: [ 133, 100 ]
                    mode: outbound
                    allow_upscale: true

        squared_thumbnail_medium_landscape:
            filters:
                thumbnail:
                    size: [ 399, 300 ]
                    mode: outbound
                    allow_upscale: true

        squared_thumbnail_large_landscape:
            filters:
                thumbnail:
                    size: [ 665, 500 ]
                    mode: outbound
                    allow_upscale: true
