symfonycasts_reset_password:
    # request_password_repository
    # Required
    # The complete namespace of the repository for the ResetPasswordRequest entity.
    # If you used make:reset-password, this will be App\Repository\ResetPasswordRequestRepository.
    request_password_repository: App\Repository\ResetPasswordRequestRepository

    # lifetime
    # Optional - Defaults to 3600 seconds
    # This is the length of time a reset password request is valid for in seconds after it has been created.
    lifetime: 7200 #3600

    # throttle_limit
    # Optional - Defaults to 3600 seconds
    # This is the length of time in seconds that must pass before a user can request a subsequent reset request.
    # Setting this value equal to or higher than lifetime will prevent a user from requesting a password reset
    # before a previous reset attempt has either 1) Been successfully completed. 2) The previous request has expired.
    # Setting this value lower than lifetime will allow a user to make several reset password requests, even if any
    # previous requests have not been successfully completed or have not expired. This would allow for cases such as
    # a user never received the reset password request email.
    throttle_limit: 7200 #3600

    # enable_garbage_collection
    # Optional - Defaults to true
    # Enable or disable the Reset Password Cleaner which handles expired reset password requests that may
    # have been left in persistence.
    enable_garbage_collection: true
