twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        'public/images': images
        'public/css': styles
        'public/bootstrap-flatly/css': bootstrap-flatly
    date:
        format: 'j F Y, H:i'
        timezone: 'Europe/Brussels'
    number_format:
        decimals: 0
        decimal_point: ','
        thousands_separator: '.'
    form_themes:
        - bootstrap_4_layout.html.twig
